### ISSUE TITLE
Allow linking to a specific build / attempt

### ISSUE THREAD

**Issue by grahamc** [samueldr/ofborg-viewer#1]
Linking to https://nix.samueldr.com/temp/?key=build.log&attempt_id=34b89ecf-71e0-490c-be6e-b4e6559a24c4 should take you to exactly that build and load the log. Even if the build is long done, it should try loading log history from the log server.

**Comment by samueldr** [comment]
For this feature, I will add two-way binding with the URL through the html5 browser history API. This should make it so that when a tab is accessed, the URL is changed to the expected one, while not actually reloading the page. This is a two-way binding since it should open the specified tab when loaded with a given URL. (The binding will also be usable for other uses)

**Comment by samueldr** [comment]
https://nix.samueldr.com/temp/index.html?attempt_id=5dbb3b13-f59c-44a7-8c6a-747526d18d39&key=build.log

And this can be yours for the low low sum of a new deploy! (Bugs or issues non-withstanding)

**Comment by samueldr** [comment]
Oh, it's still missing back/forward bindings. Working on it
